name: Unit Tests

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gets CMake
        uses: lukka/get-cmake@latest

      - name: Build simplevectors
        run: |
          mkdir build && cd build
          cmake .. -DSVECTOR_BUILD_TEST=ON -DSVECTOR_BUILD_EXAMPLE=ON

      - name: Run Unit Tests
        run: |
          cd build && make
          ctest

  MacOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build simplevectors
        run: |
          mkdir build && cd build
          cmake .. -DSVECTOR_BUILD_TEST=ON -DSVECTOR_BUILD_EXAMPLE=ON

      - name: Run Unit Tests
        run: |
          cd build && make
          ctest

  Windows:
    runs-on: windows-2022 
    steps:
      - uses: actions/checkout@v3

      - name: Build simplevectors
        run: |
          mkdir build && cd build
          cmake .. -DSVECTOR_BUILD_TEST=ON -DSVECTOR_BUILD_EXAMPLE=ON -G "Visual Studio 17 2022" -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /utf-8 /W4 /WX /EHsc"

      - name: Run Unit Tests
        run: |
          cmake --build build --config Release --parallel 10
          cd build
          ctest

  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gets CMake
        uses: lukka/get-cmake@latest

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Build simplevectors
        run: |
          mkdir build && cd build
          # build example so cmake has cpp targets to build otherwise it will complain
          cmake .. -DSVECTOR_BUILD_EXAMPLE=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic"
          make

      - name: Run Linter
        run: |
          make -C scripts/ lint

